# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
- task: DownloadSecureFile@1
  name: DownloadEnvFile
  inputs:
    secureFile: '.env.production'
- task: CopyFiles@2
  displayName: 'Copy .env.production file to working directory'
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: '.env.production'
    TargetFolder: './'
    OverWrite: true
  
- task: UseNode@1
  inputs:
    version: '20.x'  # Use the appropriate Node.js version for your project
  displayName: 'Install Node'

# Install Dependencies
- script: npm install
  displayName: 'Install Dependencies'
  
# Install dotenv-cli
- script: npm install -g dotenv-cli
  displayName: 'Install dotenv-cli'

# Run migration
- script: npm run migrate:prod
  displayName: 'Run migration'

# Build Project
- script: npm run build
  displayName: 'Build Svelte project'
  
# Publish Angular artifacts
- task: CopyFiles@2
  inputs:
    SourceFolder: './build'
    contents: '**/*'
    targetFolder: '$(Build.artifactStagingDirectory)'
    OverWrite: true
  displayName: 'Copy build artifacts'

- task: CopyFiles@2
  inputs:
    SourceFolder: './'
    contents: '.env.production'
    targetFolder: '$(Build.artifactStagingDirectory)'
    OverWrite: true
  displayName: 'Copy .env.production'

- task: CopyFiles@2
  inputs:
    SourceFolder: './'
    contents: 'package.json'
    targetFolder: '$(Build.artifactStagingDirectory)'
    OverWrite: true
  displayName: 'Copy package.json'

- task: CopyFiles@2
  inputs:
    SourceFolder: './prisma'
    contents: '**/*'
    targetFolder: '$(Build.artifactStagingDirectory)/prisma'
    OverWrite: true
  displayName: 'Copy prisma'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'