# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'police-officers-dilemma:latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      
    steps:
    - task: DockerInstaller@0
      displayName: Install docker
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: $(tag)
      
    - task: Docker@2
      displayName: Start an image
      inputs:
        command: 'start'
        container: '$(tag)'